load('TE.mat');
%plot(nanmean(TE.Photometry.data.ZS,1));
path = 'C:\Users\tcare\Documents\GitHub\CSHLPartners\Deconvolution\';

kernel = zeros(3,1) + (1/3);
data = sin(1:.1:(16 * pi))';
figure;subplot(3,2,1); plot(data);
title("Data");
subplot(3,2,2); plot(kernel);
title("Kernel");
L = numel(data);
Lx2=pow2(nextpow2(L));
fdata =  fft(data,Lx2);
subplot(3,2,3); plot(real(fdata));
title("Fourier Data");
fkernel = fft(kernel,Lx2);
subplot(3,2,4); plot(real(fkernel));
title("Fourier Kernel");
convolved = real(fdata) .* real(fkernel);
subplot(3,2,5); plot(real(convolved));
title("Fourier Multiplied");
out = ifft(convolved);
subplot(3,2,6); plot(out);
title("Final Output");
%saveas(fourier, fullfile(path, 'deconvolution_fourier.fig'));
%saveas(fourier, fullfile(path, 'deconvolution_fourier.jpg'));