delta = zeros(1, 20 * 6); 
delta(20*3) = 1;   
figure; plot(delta);
title("Before");
kernel = (1:20) / sum(1:20); 
out = conv(delta, kernel, 'full');
%out = convolvFourier(delta, kernel);
figure;
plot(out);
title("After");
out2 = deconv(out, kernel);
%out = convolvFourier(delta, kernel);
figure;
plot(out2);
title("After Deconv");
figure;
plot(kernel);